---
# Primary admin user (generic for server deployment)
admin_user: manager
admin_user_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

# Additional users (optional)
# Set this variable to create multiple users with SSH access
additional_users: []
# Example:
# additional_users:
#   - name: simon
#     key: "ssh-rsa AAAAB3NzaC1yc2EA... user@example.com"
#   - name: alice
#     key: "ssh-rsa AAAAB3NzaC1yc2EA... alice@example.com"

# For backward compatibility
user: "{{ admin_user }}"
local_key: "{{ admin_user_key }}"

# SSH configuration
ssh_port: 22
ssh_log_level: INFO
ssh_login_grace_time: 60
ssh_max_auth_tries: 3
ssh_max_sessions: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
# Automatically include all created users for SSH access
ssh_allow_users: "{{ ([admin_user] + (additional_users | default([]) | map(attribute='name') | list)) | join(',') }}"
ssh_allow_agent_forwarding: no
ssh_allow_tcp_forwarding: no
ssh_banner_path: /etc/issue.net

# Firewall configuration
firewall_ssh_rate_limit: true
firewall_ssh_rate_limit_rule: "6/minute"
firewall_allowed_ports:
  - {port: 22, proto: tcp, comment: "SSH"}

# Kernel hardening
disable_ipv6: true

# Package lists
extra_packages:
  - curl
  - vim
  - git
  - ufw
  - dfc
  - net-tools
  - htop
  - iotop

security_packages:
  - fail2ban
  - unattended-upgrades
  - aide
  - auditd
  - audispd-plugins
  - rkhunter
  - apparmor-utils

# Security settings
enable_aide: true
enable_auditd: true
enable_rkhunter: true
initialize_aide: true  # Set to false to skip AIDE database initialization (can be done manually later)
