name: CI

'on':
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint
          ansible-galaxy collection install -r requirements.yml

      - name: Run yamllint
        run: yamllint playbook.yml vars/ templates/*.j2 || true

      - name: Run ansible-lint
        run: ansible-lint playbook.yml

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        ubuntu-version: ['20.04', '22.04', '24.04']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.general ansible.posix

      - name: Run playbook syntax check
        run: |
          ansible-playbook playbook.yml --syntax-check

      - name: Test playbook in Docker
        run: |
          docker run -d --name test-ubuntu-${{ matrix.ubuntu-version }} \
            -v $PWD:/ansible:ro \
            ubuntu:${{ matrix.ubuntu-version }} \
            sleep infinity

          docker exec test-ubuntu-${{ matrix.ubuntu-version }} \
            apt-get update && apt-get install -y python3 python3-apt sudo

          docker exec test-ubuntu-${{ matrix.ubuntu-version }} \
            ansible-playbook -i localhost, -c local \
            /ansible/playbook.yml \
            --check --diff